[workspace]
members = ["taskbase"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
tokio-postgres = "0.7"
